baseURL = "http://example.org/"
languageCode = "en-us"
title = "AQuriousMind"
theme = ["reveal-hugo", "ananke"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "light"
slide_number = "true"
history = "false"