baseURL = "https://www.aquriousmind.com/"
languageCode = "en-us"
title = "AQuriousMind - Understand your Universe"
theme = ["aether"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "light"
slide_number = "true"
history = "false"

[params.hugo-swift-theme]
logo = "logo.png"

[params]
logo = "logo.png"
brand = "AQuriousMind"
description = "Read and do the experiments that changed the world."

[markup]
  [markup.highlight]
    style = "igor"